version: "3.7"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    ports:
      - 33060:33060
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: larauser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  nginx:
    image: nginx:1.17
    volumes:
      - .:/var/www/parking
      - ./docker/nginx/config:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm

  php-fpm:
    build: .
    volumes:
      - .:/var/www/parking
    links:
      - db
